# Generated by Django 6.0.2 on 2026-02-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carehome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('room_number', models.CharField(max_length=10)),
                ('medical_notes', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('care_plan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
