# Generated by Django 6.0.2 on 2026-02-15 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carehome', '0003_handover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='care_plan',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='medical_notes',
        ),
        migrations.AddField(
            model_name='resident',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resident',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='residents/'),
        ),
        migrations.AddField(
            model_name='resident',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='resident',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='CarePlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('understanding', 'Level of Understanding'), ('communication', 'Communication'), ('mobility', 'Mobility'), ('personal_care', 'Personal Care'), ('continence', 'Continence Care'), ('oral_care', 'Oral Care'), ('nutrition', 'Nutrition and Hydration'), ('skin_care', 'Skin Care'), ('social', 'Social Interests and Activities'), ('night_support', 'Night Time Support'), ('emotional', 'Emotional Support'), ('sexuality', 'Expressing Sexuality'), ('spiritual', 'Spiritual and Cultural Wellbeing'), ('health', 'Health Care'), ('medication', 'Medication Management'), ('mental', 'Mental Health'), ('end_of_life', 'End of Life Preferences'), ('breathing', 'Breathing')], max_length=50)),
                ('current_needs', models.TextField()),
                ('desired_outcomes', models.TextField()),
                ('staff_support', models.TextField()),
                ('date_started', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('resident_signature', models.CharField(blank=True, max_length=200)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_sections', to='carehome.resident')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('home_phone', models.CharField(blank=True, max_length=20)),
                ('work_phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='carehome.resident')),
            ],
        ),
    ]
